# NSW Strata Automation - SSL/TLS Production Configuration
# Task 13.1: HTTPS with Let's Encrypt
# Usage: docker-compose -f docker-compose.yml -f docker-compose.ssl.yml up -d

version: '3.8'

services:
  # Nginx SSL Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: n8n-nginx-ssl
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Nginx configuration
      - ./config/ssl-config/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL certificates (Let's Encrypt)
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      # Basic auth file
      - ./config/ssl-config/.htpasswd:/etc/nginx/.htpasswd:ro
      # Logs
      - ./logs/nginx:/var/log/nginx
    networks:
      - n8n-network
    depends_on:
      - n8n
      - grafana
      - prometheus
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Certbot for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: n8n-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    networks:
      - n8n-network

  # Override n8n to remove exposed port (proxied through Nginx)
  n8n:
    ports: []
    environment:
      - N8N_PROTOCOL=https
      - N8N_HOST=nsw-strata.example.com
      - WEBHOOK_URL=https://nsw-strata.example.com/

  # Override Grafana to remove exposed port
  grafana:
    ports: []
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.nsw-strata.example.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=false

  # Override Prometheus to remove exposed port
  prometheus:
    ports: []
