# Grafana Datasource Configuration
# Automatically provisions Prometheus as a datasource
# Task 12.1

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    version: 1
